### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by raindropworks** [sarusani/OctoPrint-ActivatePrusaHostTimer#1]
Can you maybe flesh out the description a bit more about what the M79 code does so people can learn if it's appropriate or not for them to install? I've been trying to search through Marlin and Prusa databases to references to M79 and PrusaHost and haven't been able to get any information

So while I know there's times when I do stuff with the front panel (usually cancelling a print after crash detection) and OctoPrint doesn't get what's happened and starts trying to print as soon as the printer resets, I feel like more communication -from- the Prusa to my server would be good, but I want to make sure

**Comment by sarusani** [comment]
I will add more info asap. Until then, here's a bit more info on what's the idea behind it:
https://github.com/prusa3d/Prusa-Firmware/pull/4460

Thanks for the feedback!

**Comment by raindropworks** [comment]
So if I'm reading right, integrating some of the PrusaLink features into OctoPrint?

I saw about PrusaLink and PrusaConnect when trying to figure out what this was, and told my roomate, as I bought their MK3 so they could buy an MK4, which has it built into the hardware

**Comment by sarusani** [comment]
Yes, that's about right.
PrusaLink is based on OctoPrint. So the more firmware features they'll add to support PrusaLink, the more should also be available to OctoPrint. (Most will probably require additional OctoPrint configuration or even plugins).

The first step is to tell the firmware that a host is connected, so it will start sending additional infos back to it. That's what M79 is intended for and the reason behind this plugin.

Example:
In the newest firmware (not yet publicly available) a reprint menu item on the printer has been added. (Only shown when OctoPrint is sending the M79) See: https://github.com/prusa3d/Prusa-Firmware/pull/4520

This allows you to trigger a reprint of the last print job directly from the printer without going back to OctoPrint.
So you can remove a finished print, clean your print bed and the start a reprint directly from the printer without the need to open OctoPrint.

**Comment by sarusani** [comment]
I added the example to the readme and also updated the plugin repository page to make it easier to find the info. I will add more examples in the future. 

I hope this helps!

**Comment by raindropworks** [comment]
Oh gods, and I'd -just- finished a project a few weeks ago where that reprint could have been useful. Anyway, thanks a ton!!!

**Comment by 3d-gussner** [comment]
> PrusaLink is based on OctoPrint

No PrusaLink is not based on OctoPrint.

With FW 3.14.0 which improves PrusaLink and PrusaConnect we tried to make all new features as open as possible so other host systems like OctoPrint can use these as well.
