### ISSUE TITLE
Which printers are applicable?

### ISSUE THREAD

**Issue by HolisticDeveloper** [sarusani/OctoPrint-ActivatePrusaHostTimer#3]
Do you know if these firmware features only on MK3/MK4? I have a Mini+ and I'm wondering if this plugin would be helpful.

**Comment by sarusani** [comment]
The features are available for MK3S/+, MINI/+, MK4 & XL.

 For the MINI/+, MK4 and XL all features are already available with the [current firmware](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases).\
For the MK3S/+ they will be available soon with the release of firmware 3.14.0.

**Comment by 3d-gussner** [comment]
@sarusani The M72 and M79 aren't available on MINI, MK4 and XL !

**Comment by 3d-gussner** [comment]
@sarusani Also README isn't correct

For the [MINI/+](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases), [MK4](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases) and [XL](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases) all features are available since firmware 5.1.0.

**Comment by sarusani** [comment]
@3d-gussner
The documentation mentions set ready & reprint for the 5.1.0 release. I just assumed they'll also send the action commands to PrusaLink? (Don't have a buddy firmware printer to test...)

I added a printer model selection to the settings page of the plugin and won't send M72 & M79 if it's not MK3S/+.

**Comment by 3d-gussner** [comment]
@sarusani PrusaLink on 32-bit printers uses different communication to PrusaConnect. Also Prusalink on the 32-bit is running on the 32-bit processor as the firmware and so it is possible to "internally" exchange data and instructions.
The PrusaLink on the 8-bit is running on an external device (like RPi /PC) and needs to send gcodes to the printer via serial/USB.
The PrusaConnect/PrusaLink requests to enable Set Ready/Reprint etc for the 8-bit firmware needed new gcodes or a way to communicate between PL device and Printer fw. We decided to use Gcodes to make it as open as possible.

**Comment by sarusani** [comment]
@3d-gussner
Thank you very much! I finally get it :)
I updated the documentation and will add a warning in the next release.
