### ISSUE TITLE
UI Customizer odd interaction

### ISSUE THREAD

**Issue by DaveYYZ** [sarusani/OctoPrint-ActivatePrusaHostTimer#5]
After installing this plugin, the GCode Viewer scroll bars moved from bottom and right to top and left, and failed to work correctly.  After uninstalling this plugin, GCode Viewer resumed functioning as expected.  I am running UI Customizer with the Discoranged theme applied.

**Comment by sarusani** [comment]
Thanks for the report!
It is highly possible that the CSS for the plugin influenced the GCode Viewer. I just released an update that should fix that problem. (Version 1.0.0)

**Comment by DaveYYZ** [comment]
Seems to have corrected the issue. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sarusani** [comment]
Glad it worked out. Thanks again for reporting!
